#!/usr/bin/env bash
# =============================================================================
# (C) Copyright IBM Corp. 2005-2025. All rights reserved.
#
# Distributed under the terms of the Apache License
# Version 2.0, January 2004.
# (See accompanying file LICENSE or copy at http:#www.apache.org/licenses/.)
#
# =============================================================================
sed '/\\/p' $1 | \
    sed 's/#include "/\[\[ -f $GSLROOT\/Extensions.mk \]\] \&\& cp $GSLROOT\/Extensions.mk $GSLROOT\/Extensions.mk.bak ; $MDLROOT\/bin\/mdlparser /g' | \
    sed 's/"/ ; \[\[ -f $GSLROOT\/Extensions.mk.bak \]\] \&\& cp $GSLROOT\/Extensions.mk.bak $GSLROOT\/Extensions.mk ;/g' | sed 's/\/\//\#/g'> \
        defineModels1.sh;

if [ $# -gt 1 ] && [ $2 == "-rebuild" ]; then
    gawk '{ print  $0 }' defineModels1.sh > \
        defineModels2.sh;
else
    gawk '{ print "if [ '$1' -ot " $6" ] || [ define -ot '$1' ]; then \n" $0 "\n:\nfi" }' defineModels1.sh > \
        defineModels2.sh;
fi

source defineModels2.sh;
touch $1;
rm -f defineModels1.sh;
rm -f defineModels2.sh;
touch define;
