// =================================================================
// Licensed Materials - Property of IBM
//
// "Restricted Materials of IBM"
//
// BCM-YKT-07-18-2017
//
// (C) Copyright IBM Corp. 2005-2017  All rights reserved
//
// US Government Users Restricted Rights -
// Use, duplication or disclosure restricted by
// GSA ADP Schedule Contract with IBM Corp.
//
// =================================================================

#ifndef _LENSPARSERCLASSES_
#define _LENSPARSERCLASSES_
#include "Copyright.h"

// includes

#include <list>
#include <string>

// #include "C_definition_subscriber.h"
// #include "C_subscriber.h"
// #include "C_subscription.h"
// #include "C_declaration_subscription.h"

//class definitions
#include "C_definition_trigger.h"
#include "C_definition_struct.h"
#include "C_trigger.h"
#include "C_trigger_specifier.h"
#include "C_service.h"
#include "C_declaration_trigger.h"
#include "C_declaration_publisher.h"
#include "C_declaration_service.h"
#include "C_edgeset.h"
#include "C_edgeset_extension.h"
#include "C_declaration_edgeset.h"
#include "C_argument_decl_args.h"
#include "C_directive.h"
#include "C_definition.h"
#include "C_definition_functor.h"
#include "C_definition_grid_granule.h"
#include "C_definition_type.h"
#include "C_definition_constanttype.h"
#include "C_definition_variabletype.h"
#include "C_definition_nodetype.h"
#include "C_definition_edgetype.h"
#include "C_type_definition.h"
#include "C_functor_definition.h"
#include "C_declaration_decl_decl_args.h"
#include "C_functor_declarator.h"
#include "C_functor_specifier.h"
#include "C_functor_category.h"
#include "C_declaration.h"
#include "C_declaration_int.h"
#include "C_declaration_float.h"
#include "C_declaration_repname.h"
#include "C_declaration_ndpair.h"
#include "C_declaration_ndpairlist.h"
#include "C_declaration_index_set.h"
#include "C_declaration_gridcoord.h"
#include "C_declaration_pset.h"
#include "C_declaration_list_parameter.h"
#include "C_declaration_nodeset.h"
#include "C_declaration_node_type_set.h"
#include "C_declaration_rel_nodeset.h"
#include "C_declaration_matrix_type.h"
#include "C_declaration_typedef.h"
#include "C_declaration_port.h"
#include "C_declaration_stride.h"
#include "C_declaration_repertoire.h"
#include "C_repertoire_declaration.h"
#include "C_typedef_declaration.h"
#include "C_type_specifier.h"
#include "C_initializable_type_specifier.h"
#include "C_non_initializable_type_specifier.h"
#include "C_stride_list.h"
#include "C_steps.h"
#include "C_stride.h"
#include "C_order.h"
#include "C_matrix_type_specifier.h"
#include "C_matrix_init_declarator.h"
#include "C_declarator.h"
#include "C_parameter_type_list.h"
#include "C_parameter_type.h"
#include "C_parameter_type_pair.h"
#include "C_init_attr_type_node.h"
#include "C_init_attr_type_edge.h"
#include "C_matrix_initializer.h"
#include "C_matrix_initializer_list.h"
#include "C_default_clause.h"
#include "C_matrix_initializer_clause_list.h"
#include "C_matrix_initializer_clause.h"
#include "C_matrix_initializer_expression.h"
#include "C_int_constant_list.h"
#include "C_constant_list.h"
#include "C_ndpair_clause_list.h"
#include "C_ndpair_clause_list_body.h"
#include "C_ndpair_clause.h"
#include "C_name.h"
#include "C_value.h"
#include "C_argument_list.h"
#include "C_argument_matrix.h"
#include "C_argument.h"
#include "C_argument_void.h"
#include "C_argument_constant.h"
#include "C_argument_declarator.h"
#include "C_argument_decl_args.h"
#include "C_argument_edgeset.h"
#include "C_argument_gridset.h"
#include "C_argument_grid_granule.h"
#include "C_argument_nodeset.h"
#include "C_argument_query_path_product.h"
#include "C_argument_relative_nodeset.h"
#include "C_argument_string.h"
#include "C_argument_pset.h"
#include "C_argument_argument_list.h"
#include "C_argument_ndpair_clause.h"
#include "C_argument_ndpair_clause_list.h"
#include "C_logical_OR_expression.h"
#include "C_logical_AND_expression.h"
#include "C_logical_NOT_expression.h"
#include "C_equality_expression.h"
#include "C_primary_expression.h"
#include "C_gridset.h"
#include "C_grid_granule.h"
#include "C_repname.h"
#include "C_preamble.h"
#include "C_gridnodeset.h"
#include "C_nodeset.h"
#include "C_nodeset_extension.h"
#include "C_declarator_nodeset_extension.h"
#include "C_relative_nodeset.h"
#include "C_node_type_set_specifier.h"
#include "C_node_type_set_specifier_clause.h"
#include "C_layer_set.h"
#include "C_layer_entry.h"
#include "C_name_range.h"
#include "C_layer_name.h"
#include "C_index_set_specifier.h"
#include "C_index_set.h"
#include "C_index_entry.h"
#include "C_grid_definition_body.h"
#include "C_dim_declaration.h"
#include "C_grid_translation_unit.h"
#include "C_grid_translation_declaration_list.h"
#include "C_grid_translation_declaration.h"
#include "C_grid_function_specifier.h"
#include "C_grid_function_name.h"
#include "C_composite_definition_body.h"
#include "C_composite_statement_list.h"
#include "C_composite_statement.h"
#include "C_complex_functor_definition.h"
#include "C_complex_functor_declaration_body.h"
#include "C_complex_functor_clause_list.h"
#include "C_complex_functor_clause.h"
#include "C_constructor_clause.h"
#include "C_function_clause.h"
#include "C_return_clause.h"
#include "C_connection_script_definition.h"
#include "C_connection_script_definition_body.h"
#include "C_connection_script_declaration.h"
#include "C_constant.h"
#include "C_query_path.h"
#include "C_query_path_product.h"
#include "C_query_list.h"
#include "C_query.h"
#include "C_query_field_entry.h"
#include "C_query_field_set.h"
#include "C_query_field_entry_list.h"
#include "C_system_call.h"
#include "C_phase.h"
#include "C_phase_list.h"
#include "C_phase_mapping.h"
#include "C_phase_mapping_list.h"
#include "C_declaration_init_phases.h"
#include "C_declaration_runtime_phases.h"
#include "C_declaration_load_phases.h"
#include "C_declaration_final_phases.h"
#include "C_declaration_separation_constraint.h"
#include "C_separation_constraint.h"
#include "C_separation_constraint_list.h"
#include "C_declaration_grid_granule.h"
#endif
