#!/usr/bin/env bash
#/* =================================================================
#Licensed Materials - Property of IBM
#
#"Restricted Materials of IBM"
#
#BMC-YKT-07-18-2017
#
#(C) Copyright IBM Corp. 2005-2017  All rights reserved
#
#US Government Users Restricted Rights -
#Use, duplication or disclosure restricted by
#GSA ADP Schedule Contract with IBM Corp.
#*/

sed '/\\/p' $1 | \
    sed 's/\/\//#\/\//' | \
    sed 's/#include "/cp $LENSROOT\/Extensions.mk $LENSROOT\/Extensions.mk.bak ; $MDLROOT\/bin\/mdlparser /g' | \
    sed 's/"/ ; cp $LENSROOT\/Extensions.mk.bak $LENSROOT\/Extensions.mk ;/g' > \
        defineModels1.sh;

if [ $# -gt 1 ] && [ $2 == "-rebuild" ]; then
    gawk '{ print  $0 }' defineModels1.sh > \
        defineModels2.sh;
else
    gawk '{ print "if [ '$1' -ot " $6" ] || [ define -ot '$1' ]; then \n" $0 "\n:\nfi" }' defineModels1.sh > \
        defineModels2.sh;
fi

source defineModels2.sh;	
touch $1;
rm -f defineModels1.sh;
rm -f defineModels2.sh;
touch define;
