dist: xenial

sudo: required

services:
  - docker

if: branch = for_nvu 

language: cpp

compiler:
  - gcc
    #- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
      #- llvm-toolchain-precise-3.8
    packages:
    - g++-6
      #- clang-3.8
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
  #- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

cache:
  directories:
  - mpich

before_install:
  - sh ./get_ompi.sh
  - echo "Testing Docker Hub credentials"
    #- docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - echo "Docker Hub credentials are working"
    #- docker build -t build-springxd-base .

script:
  - source set_env
  - ./build_script -p LINUX --as-MGS

    #script:
    #  - docker ps -a

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
    #  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub"; fi
    #  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
    #  - export REPO=jayjohnson/springxd-base
    #  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    #  - docker build -f Dockerfile -t $REPO:$COMMIT .
    #  - docker tag $REPO:$COMMIT $REPO:$TAG
    #  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    #  - docker push $REPO
