dist: xenial

sudo: required

services:
  - docker

if: branch = for_nvu 

language: cpp

compiler:
  - gcc
    #- clang

env:
  global:
    - secure: "jV9WdgzDemtQaw83SwFKbDfc1/5BPE4DGQGrrwHRIHCqw9NzCULGEi9CL41hWIBv9zHjX/zpAJzqKQUsZusEjsmud4pg5Gu6I2OA3KLFurG11+Bipcs9f4MUnLwa4dhIHrIColYy4ul4QYiCGUaNr12Idj+mELUzo79Sc3a/k3MOq+J01QvNKVrpUCn+MZMR1gHepZSMqxJw5/QE+6crN7WDOqv3D6ZlYQvha2ZDKzJjBQ9nVe4NNCrK8qrwWKkSwi8cPEPUCEQogn7AO4OO4M4crJ6PdhNo+I2N/u7PIgA9UoyV4gpJSJaHI3DSOuXMp4U48g9s2eccbuJGFF3deJ5SWUYm4Y2ZPfK/PN5+dYR7w3vgu8IUVW8A/ac+Bez0ABiuSVJDCqCwu2KtjD3sL910aHmfXsZS09Vhws+xLkWpSev7v1TKCPQdD2CbmnEIkJMQ7NJdRrpn79O/F0nzYmP4XylfG3M2AuHsmVF95ZtgAMkAir/0ou789xNIsknl79SyFQRgeLdBbsjVrDPfAliTmNOH1tLLX+n4ezy6sZQFSPXL+HoJ843sSv+1ZsFjBPc5I6h7qhXTpV26xl/Fuy9SNZFT+e5khd7N3QKD6YaYND/2mJ2LfH3FBtjRpl5FAAFIJRsgehX+3MREy3iYR3cx4jIyrmNQt1f2sOaDsA8="

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ppa:graphics-drivers/ppa
      #- llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - nvidia-driver-415
      #- clang-3.8
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
  #- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

cache:
  directories:
  - mpich
  - ompi

before_install:
  - ubuntu-drivers list
  - sh ./get_ompi.sh
  - echo "Testing Docker Hub credentials"
    #- docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - echo "Docker Hub credentials are working"
    #- docker build -t build-springxd-base .

script:
  - source set_env
  - ./build_script -p LINUX --as-MGS

    #script:
    #  - docker ps -a

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
    #  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub"; fi
    #  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
    #  - export REPO=jayjohnson/springxd-base
    #  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    #  - docker build -f Dockerfile -t $REPO:$COMMIT .
    #  - docker tag $REPO:$COMMIT $REPO:$TAG
    #  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    #  - docker push $REPO
