#line 1 "MdlLexer.cpp"

#line 3 "MdlLexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int MdlLexer::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[420] =
    {   0,
        0,    0,   89,   87,   83,   82,   87,   87,   84,   39,
       42,   87,   87,   38,   87,   79,   36,   87,   37,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   78,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   87,   83,   33,    0,
       31,    0,   79,    0,    0,   85,   81,   79,    0,   40,
       34,   32,   35,   41,   73,   74,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   78,   77,   78,   73,   73,

       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       30,   72,    0,   43,    0,    0,   85,   81,    0,   80,
       75,   74,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   27,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   77,   77,   73,   73,   73,   73,
       73,    5,   73,   73,   73,   73,   73,   73,   86,   75,
       76,   73,   73,   73,   73,   10,   73,   73,   73,   73,
       73,   14,   73,   73,   73,   73,   73,   73,   15,   73,
       73,   57,   73,   28,   73,   73,   73,   73,   73,   73,

       73,   73,   73,   73,   73,   73,    2,    3,   73,   73,
       73,    6,   73,   73,   44,   73,   69,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   45,    7,    4,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   22,   73,   54,   47,   73,   73,   73,   73,    8,

        1,   73,   73,   73,   73,   46,   11,   73,   67,   52,
       73,   73,   13,   73,   73,   73,   73,   73,   73,   73,
       73,   16,   73,   73,   73,   73,   73,   73,   50,   73,
       73,   73,   18,   71,   20,   73,   73,   73,   68,   73,
       62,   12,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   17,   25,   73,   23,   73,   51,   73,   73,
       73,   73,   73,   63,    9,   73,   73,   29,   73,   73,
       73,   58,   73,   48,   61,   73,   73,   73,   73,   73,
       73,   73,   73,   49,   60,   70,   53,   55,   66,   26,
       73,   73,   73,   19,   73,   73,   73,   56,   73,   73,

       73,   73,   73,   24,   73,   59,   73,   64,   73,   73,
       73,   73,   73,   73,   73,   73,   65,   21,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    1,    1,
        1,    8,    9,    1,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,    1,   14,
       15,   16,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   18,   24,   18,   18,   25,   18,   26,   27,   28,
       18,   29,   30,   31,   32,   33,   18,   18,   18,   18,
        1,    1,    1,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   18,   44,   45,   46,   47,
       48,   49,   18,   50,   51,   52,   53,   54,   55,   56,
       57,   58,    1,   59,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1
    } ;

static const flex_int16_t yy_base[432] =
    {   0,
        0,    0,  829,  830,  826,  830,  812,    0,  830,  819,
      830,  812,  811,  812,   52,   50,   51,  807,   52,  787,
       35,   38,   40,   41,   42,   39,   45,   61,   48,   68,
       66,   65,   72,   74,   53,   77,   76,   78,   79,   94,
       87,   89,   96,   81,   98,   92,  761,  817,  830,  813,
      830,  122,  131,  806,  808,    0,  128,  142,  137,  830,
      830,  830,  830,  830,  781,  780,   28,  117,  122,  124,
      120,  126,  140,  132,  128,  134,  159,  143,  152,  150,
      148,  151,  153,  155,  156,  157,  160,  161,  163,  164,
      167,  170,  172,  180,  176,  779,  778,    0,  182,  187,

      178,  184,  189,  190,  191,  193,  194,  198,  199,  200,
      830,  830,  234,  830,  803,  798,    0,  227,  796,  795,
      773,  772,  215,  205,  219,  224,  223,  225,  201,  231,
      233,  234,  235,  227,  237,  242,  240,  248,  251,  241,
      269,  253,  257,  254,  270,  259,  260,  266,  261,  263,
      268,  276,  265,  279,  771,    0,  280,  284,  285,  289,
      292,  770,  290,  294,  295,  296,  298,  299,  830,  769,
        0,  302,  308,  305,  311,  318,  316,  317,  319,  321,
      322,  333,  327,  325,  342,  312,  344,  337,  352,  339,
      329,  768,  345,  358,  341,  354,  359,  360,  361,  364,

      365,  368,  366,  372,  386,  376,  767,  766,  378,  380,
      381,  765,  382,  383,  764,  384,  763,  387,  390,  394,
      392,  398,  388,  402,  404,  412,  102,  405,  407,  409,
      410,  415,  413,  418,  417,  416,  428,  427,  429,  430,
      434,  431,  435,  437,  440,  438,  439,  444,  454,  458,
      446,  459,  447,  453,  465,  461,  762,  761,  760,  468,
      460,  469,  470,  471,  474,  476,  477,  481,  479,  482,
      483,  487,  489,  493,  501,  499,  480,  504,  506,  511,
      508,  509,  513,  515,  516,  510,  518,  520,  529,  519,
      527,  759,  534,  758,  757,  523,  535,  536,  537,  756,

      755,  538,  541,  544,  542,  754,  753,  545,  752,  751,
      546,  552,  750,  554,  556,  561,  555,  558,  562,  563,
      566,  749,  571,  570,  579,  574,  577,  578,  748,  584,
      586,  593,  747,  746,  589,  588,  592,  596,  745,  590,
      744,  743,  598,  599,  601,  603,  605,  606,  607,  608,
      614,  612,  742,  741,  620,  740,  618,  739,  622,  623,
      624,  626,  625,  738,  737,  628,  633,  736,  635,  636,
      637,  735,  640,  734,  733,  642,  644,  650,  659,  651,
      657,  666,  661,  732,  731,  730,  729,  728,  727,  726,
      662,  663,  648,  725,  664,  665,  669,  724,  671,  672,

      673,  674,  675,  721,  676,  714,  690,  713,  677,  682,
      692,  694,  691,  696,  686,  698,  709,  708,  830,  745,
      737,  736,  749,  753,  734,  732,  727,  547,  364,  297,
      242
    } ;

static const flex_int16_t yy_def[432] =
    {   0,
      419,    1,  419,  419,  419,  419,  419,  420,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  422,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  419,  419,  419,  420,
      419,  419,  419,  419,  423,  424,  419,  419,  419,  419,
      419,  419,  419,  419,  421,  425,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  426,  427,  428,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      419,  419,  419,  419,  423,  423,  424,  419,  419,  419,
      429,  425,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  427,  430,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  419,  429,
      431,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,    0,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419
    } ;

static const flex_int16_t yy_nxt[890] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   20,   37,   38,   39,   20,   40,
       20,   20,   41,   20,   42,   20,   20,   20,   20,   20,
       43,   44,   45,   46,   20,   20,   20,   20,   47,   55,
       57,  121,   58,   56,   60,   61,   63,   64,   66,   67,
       59,   66,   66,   66,   66,   66,   69,   70,   66,  123,
       79,   66,   68,   72,   76,   77,   66,   95,   59,   96,
       73,   75,   78,   74,   66,   71,   81,   83,   66,   66,

       82,   66,   84,   89,   87,   66,   90,   66,   80,   66,
       98,   66,   66,   92,   66,   85,   91,   86,   88,  100,
       66,   93,   66,   99,   94,   66,  101,   66,  102,   66,
      108,   66,   57,  104,  113,  121,  105,  106,  103,  110,
      118,   57,   59,   58,  109,  119,  119,  107,   59,  120,
      121,   59,   57,  121,   58,  121,  271,  121,  127,  121,
       59,  121,   59,  124,  126,  121,   59,  121,  128,   59,
      132,  125,  129,  121,  130,  134,  121,  137,  131,  138,
       59,  121,  133,  121,  121,  121,  121,  139,  121,  121,
      121,  142,  121,  121,  121,  145,  121,  121,  149,  140,

      121,  135,  141,  121,  143,  121,  144,  147,  146,  121,
      136,  121,  148,  121,  152,  121,  150,  121,  153,  151,
      121,  158,  121,  121,  121,  154,  121,  121,  160,  157,
      159,  121,  121,  121,  121,  179,  161,  163,  121,  118,
      164,  162,  168,  165,   57,  171,  113,   59,  121,  167,
      166,  173,  121,  172,   59,  174,  121,  121,  121,  177,
      121,  175,  176,  178,  121,   59,  121,  121,  121,  181,
      121,  182,   59,  121,  121,  121,  180,  187,  184,  183,
      186,  121,  188,  190,  121,  191,  121,  121,  185,  189,
      121,  193,  121,  121,  121,  195,  121,  197,  121,  121,

      156,  121,  121,  121,  192,  194,  203,  196,  199,  121,
      201,  198,  121,  121,  205,  202,  204,  121,  121,  200,
      209,  206,  121,  121,  207,  121,  211,  121,  121,  121,
      212,  121,  121,  208,  215,  121,  217,  214,  121,  210,
      216,  121,  218,  213,  121,  121,  219,  222,  223,  121,
      121,  121,  121,  225,  121,  121,  220,  229,  121,  227,
      121,  234,  121,  226,  221,  230,  121,  170,  224,  232,
      121,  235,  121,  228,  121,  121,  231,  121,  121,  236,
      240,  237,  238,  243,  233,  121,  239,  121,  244,  241,
      242,  121,  121,  121,  121,  248,  245,  121,  121,  121,

      252,  121,  247,  250,  251,  121,  249,  254,  246,  121,
      255,  121,  253,  121,  121,  121,  121,  121,  257,  121,
      121,  121,  256,  121,  261,  121,  263,  121,  264,  260,
      265,  121,  258,  259,  262,  121,  266,  121,  121,  270,
      121,  273,  121,  121,  267,  121,  121,  277,  121,  121,
      121,  121,  272,  268,  274,  269,  276,  278,  279,  275,
      121,  121,  121,  121,  121,  280,  281,  121,  121,  286,
      121,  121,  121,  121,  288,  283,  289,  121,  285,  121,
      121,  284,  287,  282,  291,  297,  121,  121,  292,  290,
      293,  121,  121,  121,  121,  294,  296,  295,  121,  300,

      299,  121,  121,  121,  121,  298,  302,  121,  301,  121,
      121,  306,  121,  121,  121,  121,  121,  305,  303,  309,
      121,  304,  121,  311,  318,  308,  121,  307,  316,  310,
      312,  315,  121,  317,  121,  321,  313,  121,  319,  121,
      320,  121,  121,  121,  121,  314,  121,  324,  121,  121,
       98,  121,  121,  121,  326,  328,  121,  323,  329,  322,
      121,  327,  121,  330,  325,  332,  331,  121,  121,  121,
      121,  121,  333,  334,  121,  121,  338,  121,  121,  121,
      343,  337,  336,  342,  335,  121,  340,  121,  121,  121,
      347,  121,  345,  341,  121,  121,  121,  339,  350,  121,

      349,  344,  346,  121,  121,  348,  355,  121,  352,  353,
      121,  121,  121,  351,  354,  357,  358,  121,  356,  121,
      361,  121,  121,  121,  363,  121,  121,  362,  360,  121,
      364,  121,  121,  365,  121,  359,  121,  366,  121,  121,
      121,  121,  368,  371,  372,  121,  374,  121,  367,  377,
      369,  121,  375,  121,  370,  121,  121,  121,  121,  121,
      379,  121,  376,  382,  373,  381,  121,  378,  121,  121,
      121,  385,  380,  121,  384,  121,  383,  121,  389,  392,
      393,  121,  391,  121,  121,  386,  387,  396,  388,  394,
      121,  395,  121,  390,  121,  121,  121,  121,  121,  121,

      400,  399,  121,  397,  121,  121,  121,  121,  121,  121,
      121,  406,  409,  398,  401,  121,  403,  402,  405,  121,
      407,  408,  404,  121,  121,  121,  410,  121,  411,  121,
      155,  121,  417,  412,  413,   96,  414,  122,  415,   97,
       65,  121,  121,  416,  418,   50,  121,  121,   50,  115,
      115,  115,  115,  117,  121,  117,  117,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,

      121,  121,  171,  121,  156,  171,  121,  120,  120,  169,
      116,  156,   98,  121,  121,  116,  114,  112,   48,  111,
       66,   62,   54,   53,   52,   51,   49,   48,  419,    3,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419
    } ;

static const flex_int16_t yy_chk[890] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   15,
       16,   67,   16,   15,   17,   17,   19,   19,   21,   21,
       16,   22,   26,   23,   24,   25,   22,   23,   27,   67,
       28,   29,   21,   24,   26,   26,   35,   35,   16,   36,
       24,   25,   27,   24,   28,   23,   29,   30,   32,   31,

       29,   30,   30,   32,   31,   33,   32,   34,   28,   37,
       36,   38,   39,   33,   44,   30,   32,   30,   31,   38,
       41,   33,   42,   37,   34,   46,   39,   40,   40,   43,
       44,   45,   52,   41,   52,  227,   42,   43,   40,   46,
       57,   53,   52,   53,   45,   59,   59,   43,   57,   59,
       68,   53,   58,   71,   58,   69,  227,   70,   71,   72,
       52,   75,   58,   68,   70,   74,   57,   76,   71,   53,
       75,   69,   72,   73,   73,   77,   78,   78,   74,   79,
       58,   81,   76,   80,   82,   79,   83,   80,   84,   85,
       86,   83,   77,   87,   88,   86,   89,   90,   90,   81,

       91,   77,   82,   92,   84,   93,   85,   88,   87,   95,
       77,  101,   89,   94,   93,   99,   91,  102,   94,   92,
      100,  100,  103,  104,  105,   95,  106,  107,  102,   99,
      101,  108,  109,  110,  129,  129,  103,  105,  124,  118,
      106,  104,  110,  107,  113,  431,  113,  118,  123,  109,
      108,  124,  125,  123,  113,  124,  127,  126,  128,  127,
      134,  125,  126,  128,  130,  118,  131,  132,  133,  131,
      135,  132,  113,  137,  140,  136,  130,  137,  134,  133,
      136,  138,  138,  140,  139,  141,  142,  144,  135,  139,
      143,  143,  146,  147,  149,  145,  150,  146,  153,  148,

      430,  151,  141,  145,  142,  144,  151,  145,  148,  152,
      149,  147,  154,  157,  153,  150,  152,  158,  159,  148,
      159,  154,  160,  163,  157,  161,  161,  164,  165,  166,
      163,  167,  168,  158,  166,  172,  168,  165,  174,  160,
      167,  173,  172,  164,  175,  186,  173,  176,  176,  177,
      178,  176,  179,  178,  180,  181,  174,  182,  184,  180,
      183,  186,  191,  179,  175,  183,  182,  429,  177,  185,
      188,  187,  190,  181,  195,  185,  184,  187,  193,  188,
      191,  189,  189,  194,  185,  189,  190,  196,  195,  193,
      193,  194,  197,  198,  199,  199,  196,  200,  201,  203,

      203,  202,  198,  201,  202,  204,  200,  205,  197,  206,
      206,  209,  204,  210,  211,  213,  214,  216,  210,  205,
      218,  223,  209,  219,  216,  221,  219,  220,  220,  214,
      221,  222,  211,  213,  218,  224,  222,  225,  228,  226,
      229,  229,  230,  231,  223,  226,  233,  233,  232,  236,
      235,  234,  228,  224,  230,  225,  232,  234,  235,  231,
      238,  237,  239,  240,  242,  236,  237,  241,  243,  242,
      244,  246,  247,  245,  244,  239,  245,  248,  241,  251,
      253,  240,  243,  238,  247,  253,  254,  249,  248,  246,
      249,  250,  252,  261,  256,  250,  252,  251,  255,  256,

      255,  260,  262,  263,  264,  254,  261,  265,  260,  266,
      267,  265,  269,  277,  268,  270,  271,  264,  262,  268,
      272,  263,  273,  270,  277,  267,  274,  266,  275,  269,
      271,  274,  276,  276,  275,  280,  272,  278,  278,  279,
      279,  281,  282,  286,  280,  273,  283,  283,  284,  285,
      428,  287,  290,  288,  285,  287,  296,  282,  288,  281,
      291,  286,  289,  289,  284,  291,  290,  293,  297,  298,
      299,  302,  293,  296,  303,  305,  302,  304,  308,  311,
      311,  299,  298,  308,  297,  312,  304,  314,  317,  315,
      316,  318,  314,  305,  316,  319,  320,  303,  319,  321,

      318,  312,  315,  324,  323,  317,  325,  326,  321,  323,
      327,  328,  325,  320,  324,  327,  328,  330,  326,  331,
      332,  336,  335,  340,  336,  337,  332,  335,  331,  338,
      337,  343,  344,  338,  345,  330,  346,  340,  347,  348,
      349,  350,  344,  347,  348,  352,  350,  351,  343,  355,
      345,  357,  351,  355,  346,  359,  360,  361,  363,  362,
      359,  366,  352,  362,  349,  361,  367,  357,  369,  370,
      371,  367,  360,  373,  366,  376,  363,  377,  373,  378,
      379,  393,  377,  378,  380,  369,  370,  382,  371,  380,
      381,  381,  379,  376,  383,  391,  392,  395,  396,  382,

      393,  392,  397,  383,  399,  400,  401,  402,  403,  405,
      409,  401,  405,  391,  395,  410,  397,  396,  400,  415,
      402,  403,  399,  407,  413,  411,  407,  412,  409,  414,
      427,  416,  415,  410,  411,  426,  412,  425,  413,  422,
      421,  418,  417,  414,  416,  420,  408,  406,  420,  423,
      423,  423,  423,  424,  404,  424,  424,  398,  394,  390,
      389,  388,  387,  386,  385,  384,  375,  374,  372,  368,
      365,  364,  358,  356,  354,  353,  342,  341,  339,  334,
      333,  329,  322,  313,  310,  309,  307,  306,  301,  300,
      295,  294,  292,  259,  258,  257,  217,  215,  212,  208,

      207,  192,  170,  162,  155,  122,  121,  120,  119,  116,
      115,   97,   96,   66,   65,   55,   54,   50,   48,   47,
       20,   18,   14,   13,   12,   10,    7,    5,    3,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "mdl.l"
#line 2 "mdl.l"
// =============================================================================*/
// (C) Copyright IBM Corp. 2005-2025. All rights reserved.
//
// Distributed under the terms of the Apache License
// Version 2.0, January 2004.
// (See accompanying file LICENSE or copy at http://www.apache.org/licenses/.)
//                                                                  */
// =============================================================================*/
#line 755 "MdlLexer.cpp"
/* Digits, letters and alphanums */
#line 29 "mdl.l"

#include <iostream>
#include <string>
#include "MdlLexer.h"
using namespace std;
#line 763 "MdlLexer.cpp"
#line 764 "MdlLexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 36 "mdl.l"

#line 898 "MdlLexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 420 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 830 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( STRING );  
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( BOOL );  
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( CHAR );
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( SHORT );
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( INT );
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( LONG );
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( FLOAT );
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( DOUBLE );
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( UNSIGNED );
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 73 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( EDGE );
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 77 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( EDGESET );
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 81 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( EDGETYPE );
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( FUNCTOR );
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 89 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( GRID );
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 93 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( NODE );
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( NODESET );
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 101 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( NODETYPE );
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( SERVICE );
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 109 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( REPERTOIRE );
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 113 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( TRIGGER );
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 117 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( TRIGGEREDFUNCTION );
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 121 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( SERIAL );
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 125 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( PARALLEL );
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 129 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( PARAMETERSET );
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 133 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( OPTIONAL );
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 137 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( NDPAIRLIST );
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 141 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( PRE );
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 145 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( POST );
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 149 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( FRAMEWORK );
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 153 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( OR );
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 157 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( AND );
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 161 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( EQUAL );
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 165 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( NOT_EQUAL );
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 169 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( LESS_EQUAL );
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 173 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( GREATER_EQUAL );
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 177 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( LESS );
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 181 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( GREATER );
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 185 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( DOT );
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 189 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( AMPERSAND );
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 193 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( LEFTSHIFT );
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 197 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( RIGHTSHIFT );
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 201 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( STAR );
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 205 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return ( ELLIPSIS );
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 209 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( _TRUE );
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 213 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( _FALSE );
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 217 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( DERIVED );
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 221 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( STRUCT );
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 225 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( INTERFACE );
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 229 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( CONNECTION );
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 233 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( PRENODE );
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 237 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( POSTNODE );
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 241 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( EXPECTS );
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 245 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( IMPLEMENTS );
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 249 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( SHARED );
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 253 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( INATTRPSET );
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 257 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( OUTATTRPSET );
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 261 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( PSET );
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 265 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( INITPHASE );
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 269 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( RUNTIMEPHASE );
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 273 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( FINALPHASE );
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 277 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( LOADPHASE );
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 281 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( CONSTANT );
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 285 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( VARIABLE );
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 289 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( USERFUNCTION );
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 293 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( PREDICATEFUNCTION );
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 297 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( INITIALIZE );
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 301 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( EXECUTE );
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 305 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( CATEGORY );
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 309 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( VOID );
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 313 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( GRIDLAYERS );
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 317 "mdl.l"
{
   yylloc->first_line = lineCount;
   return ( THREADS );
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 321 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->P_string = new string(yytext); 
   string::iterator b;
   b = yylval->P_string->begin(); 
   yylval->P_string->erase(b);
   string::iterator e;
   e = yylval->P_string->end(); 
   yylval->P_string->erase(--e);
   //cout << "yytext = " << *yylval->P_string << endl;
   return ( STRING_LITERAL ); 
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 333 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->P_string = new string (yytext); 
   //cout << "yytext = " << yytext << endl; 
   return(IDENTIFIER); 
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 339 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->P_string = new string (yytext); 
   //cout << "yytext = " << yytext << endl; 
   return(IDENTIFIER); 
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 345 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->P_string = new string (yytext); 
   //cout << "yytext = " << yytext << endl; 
   return(IDENTIFIER); 
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 351 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->P_string = new string (yytext); 
   //cout << "yytext = " << yytext << endl; 
   return(IDENTIFIER); 
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 357 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->P_string = new string (yytext); 
   //cout << "yytext = " << yytext << endl; 
   return(IDENTIFIER); 
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 363 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->P_string = new string (yytext); 
   //cout << "yytext = " << yytext << endl; 
   return(IDENTIFIER); 
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 369 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->V_int= atoi (yytext); 
   //cout << "yytext = " << yytext << endl;
   return(INT_CONSTANT); 
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 375 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->V_double= atof (yytext); 
   //cout << "yytext = " << yytext << endl;
   return(DOUBLE_CONSTANT); 
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 381 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   yylval->V_double= atof (yytext);  
   //cout << "yytext = " << yytext << endl;
   return(DOUBLE_CONSTANT); 
}
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 387 "mdl.l"
{ 
   lineCount++; 
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 390 "mdl.l"
;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 391 "mdl.l"
{ 
   skip_proc(); 
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 394 "mdl.l"
{ 
   /* Skip C++ style comments */
}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 397 "mdl.l"
{
   /* Count newlines in block comments */
   for(int i = 0; i < yyleng; i++) {
      if(yytext[i] == '\n') lineCount++;
   }
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 403 "mdl.l"
{ 
   yylloc->first_line = lineCount;
   return (yytext[0]); 
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 407 "mdl.l"
ECHO;
	YY_BREAK
#line 1680 "MdlLexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
size_t yyFlexLexer::LexerInput( char* buf, size_t /* max_size */ )
#else
size_t yyFlexLexer::LexerInput( char* buf, size_t max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, size_t size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 420 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 420 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 419);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 407 "mdl.l"



